from variables.embeddings import NUM_TOKENS, NUM_WORDS

EMBEDDING_SIZE = 100
BATCH_SIZE = 21
INPUT_STEPS = 36
OUTPUT_STEPS = 27
ESTATE_SIZE = 100
WDSTATE_SIZE = 100
TDSTATE_SIZE = 100
PDOUT_SIZE = 200
SDOUT_SIZE = 200
TRAIN_EPOCHS = 500

TRAIN_SET = 0.9
VALIDATION_SET = 0.1

ENUMBER = 3
WDNUMBER = 3
TDNUMBER = 3
PDHEADS = 1
SDHEADS = 1

WORD_SIZE = NUM_WORDS
TOKEN_SIZE = NUM_TOKENS
