RESOURCES = "resources"

DATA_SETS = RESOURCES + "/data_sets"
SENTENCES = DATA_SETS + "/sentences.txt"
FILTERED = DATA_SETS + "/filtered.txt"
BATCHES = DATA_SETS + "/batches.pickle"
METHODS = DATA_SETS + "/methods.xml"
VEC_METHODS = DATA_SETS + "/methods.pickle"
EMBEDDINGS = DATA_SETS + "/word2vec.pickle"
CONTEXTS = DATA_SETS + "/contexts.pickle"
PRETRAIN_SETS = DATA_SETS + "/pretrain_sets"

NETS = RESOURCES + "/nets"

WORD2VEC = NETS + "/word2vec"
WORD2VEC_MODEL = WORD2VEC + "/model.ckpt"
WORD2VEC_LOG = WORD2VEC + "/train.log"

SEQ2SEQ = NETS + "/seq2seq"
ANALYSER_LOG = SEQ2SEQ + "/analyser.log"
Q_FUNCTION_LOG = SEQ2SEQ + "/q-function.log"
CONTRACTS_LOG = SEQ2SEQ + "/contracts.log"
GENERATOR_LOG = SEQ2SEQ + "/generator.log"
ANALYSER_BATCHES = SEQ2SEQ + "/analyser-batches.pickle"
Q_FUNCTION_BATCHES = SEQ2SEQ + "/q-function-batches.pickle"
