from constants import embeddings

BATCH_SIZE = 5

INPUT_SIZE = 50
INPUTS_STATE_SIZE = 50

CONDITIONS_STATE_SIZE = 50
SEQUENCE_STATE_SIZE = 50

STRINGS_STATE_SIZE = 50
STRINGS_HIDDEN_SIZE = 50

NUM_ENCODERS = 1
NUM_DECODERS = 1
CONDITIONS_NUM_HEADS = 1
SEQUENCE_NUM_HEADS = 1

TRAIN_EPOCHS = 1000

TOP = 3
TEST_SET = 0.1
TRAIN_SET = 0.8
VALIDATION_SET = 0.1
MINIMUM_DATA_SET_LENGTH = 1
SEED = 5640

L2_LOSS_WEIGHT = 0.001

NUM_TOKENS = len(embeddings.tokens())
NUM_LABELS = len(embeddings.labels())
NUM_WORDS = len(embeddings.words())
