BATCH_SIZE = 4

EMBEDDING_SIZE = 100

INPUTS_STATE_SIZE = 500
INPUT_HIDDEN_SIZE = 500
TREE_OUTPUT_STATE_SIZE = 500
STRING_OUTPUT_STATE_SIZE = 500

L2_LOSS_WEIGHT = 0.001

TRAIN_EPOCHS = 500

TEST_SET = 0.1
TRAIN_SET = 0.8
VALIDATION_SET = 0.1
MINIMUM_DATA_SET_LENGTH = 1

WINDOW_SIZE = 7

OUTPUT_TYPE = "tree"
FLATTEN_TYPE = "bfs"
FILLING = True
MAX_PARAM = 5
